axelarnetwork/axelar-amplifier-stellar

contract/Cargo.toml, contract/src/admin.rs, contract/src/gateway.rs, contract/src/test.rs, executable-example/Cargo.toml, executable-example/src/lib.rs, executable/Cargo.toml, executable/src/executable.rs
```bash
>  cargo test
...
failures:
test::approve_contract_call
test::call_contract
test::hashForEpoch_epochForHash
test::single_operator_signer
test::transfer_operatorship
test result: FAILED. 13 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.35s
```
=> feat(Gateway): using secp256k1 and keccak256

Cargo.lock, Cargo.toml, contracts/axelar-operators/Cargo.toml, contracts/axelar-operators/src/contract.rs, contracts/axelar-operators/src/error.rs, contracts/axelar-operators/src/event.rs, contracts/axelar-operators/src/lib.rs, contracts/axelar-operators/src/storage_types.rs, contracts/axelar-operators/src/test.rs, contracts/axelar-soroban-interfaces/src/axelar_operators.rs, contracts/axelar-soroban-interfaces/src/lib.rs
Implement Operators contract in Soroban as per [AXE-3402](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/21?selectedIssue=AXE-3402)
Note: Still need to implement Soroban version of `executeContract` function
[AXE-3402]: https://axelarnetwork.atlassian.net/browse/AXE-3402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: operators contract

contracts/axelar-operators/src/contract.rs, contracts/axelar-operators/src/test.rs, contracts/axelar-soroban-interfaces/src/axelar_operators.rs
[AXE-3893]
[AXE-3893]: https://axelarnetwork.atlassian.net/browse/AXE-3893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(Operators): execute method

Cargo.lock, Cargo.toml, README.md, contracts/axelar-auth-verifier/src/contract.rs, contracts/axelar-auth-verifier/src/event.rs, contracts/axelar-auth-verifier/src/storage_types.rs, contracts/axelar-auth-verifier/src/test.rs, contracts/axelar-auth-verifier/src/testutils.rs, contracts/axelar-gateway/src/contract.rs, contracts/axelar-gateway/src/event.rs, contracts/axelar-gateway/src/storage_types.rs, contracts/axelar-gateway/src/testutils.rs, contracts/axelar-soroban-interfaces/src/axelar_auth_verifier.rs, contracts/axelar-soroban-interfaces/src/axelar_executable.rs, contracts/axelar-soroban-interfaces/src/axelar_gateway.rs, contracts/axelar-soroban-interfaces/src/interchain_token_service.rs, contracts/axelar-soroban-interfaces/src/test.rs, contracts/axelar-soroban-interfaces/src/types.rs, integration-tests/tests/gmp.rs, packages/axelar-soroban-std/src/types.rs
[AXE-4301]
[AXE-4301]: https://axelarnetwork.atlassian.net/browse/AXE-4301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(soroban-sdk)!: upgrade to soroban v21 preview

optimize.sh
- There was an error while executing the `optimize.sh`, It was trying to optimize the contract even there's no corresponding wasm file exists.
- Optimize the contract only when the wasm file exists.
```
./optimize.sh
Reading: target/wasm32-unknown-unknown/release/axelar_auth_verifier.wasm (13677 bytes)
Optimized: target/wasm32-unknown-unknown/release/axelar_auth_verifier.optimized.wasm (11881 bytes)
Reading: target/wasm32-unknown-unknown/release/axelar_gas_service.wasm (4745 bytes)
Optimized: target/wasm32-unknown-unknown/release/axelar_gas_service.optimized.wasm (4112 bytes)
Reading: target/wasm32-unknown-unknown/release/axelar_gateway.wasm (9560 bytes)
Optimized: target/wasm32-unknown-unknown/release/axelar_gateway.optimized.wasm (8275 bytes)
Reading: …
```
=> fix(optimize.sh): update contract the optimize script only when the wasm file exists.

.gitignore, README.md, contracts/axelar-gas-service/src/test.rs, contracts/axelar-gateway/src/test.rs, contracts/axelar-operators/src/test.rs, contracts/axelar-soroban-interfaces/src/test.rs, integration-tests/tests/gmp.rs, packages/axelar-soroban-std/src/testutils.rs
[AXE-5747](https://axelarnetwork.atlassian.net/browse/AXE-5747)
[AXE-5747]: https://axelarnetwork.atlassian.net/browse/AXE-5747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(axelar-gateway): increase gateway coverage and add coverage report

contracts/axelar-gateway/src/auth.rs, contracts/axelar-gateway/src/contract.rs, contracts/axelar-gateway/src/event.rs, contracts/axelar-gateway/src/storage_types.rs, contracts/axelar-gateway/src/test.rs, contracts/axelar-gateway/src/testutils.rs, contracts/axelar-soroban-interfaces/src/axelar_gateway.rs
[AXE-5723](https://axelarnetwork.atlassian.net/browse/AXE-5723)
- TODO: add docstring about how `bypass_rotation_delay` supposed to be used.
[AXE-5723]: https://axelarnetwork.atlassian.net/browse/AXE-5723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(gateway): add rotation delay governance

contracts/axelar-gateway/src/auth.rs, contracts/axelar-gateway/src/event.rs, contracts/axelar-gateway/src/test.rs, contracts/axelar-soroban-interfaces/src/types.rs
- [AXE-5914](https://axelarnetwork.atlassian.net/browse/AXE-5914)
- [AXE-6043](https://axelarnetwork.atlassian.net/browse/AXE-6043): Removed signers data due to stellar's [event size limit (8KB max)](https://developers.stellar.org/docs/networks/resource-limits-fees)
[AXE-5914]: https://axelarnetwork.atlassian.net/browse/AXE-5914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AXE-6043]: https://axelarnetwork.atlassian.net/browse/AXE-6043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(gateway)!: update rotate signers event

contracts/axelar-gateway/src/contract.rs, contracts/axelar-gateway/src/event.rs, contracts/axelar-gateway/src/test.rs
[AXE-6048](https://axelarnetwork.atlassian.net/browse/AXE-6048)
[AXE-6048]: https://axelarnetwork.atlassian.net/browse/AXE-6048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: update execute event

contracts/axelar-gateway/src/auth.rs, contracts/axelar-gateway/src/contract.rs, contracts/axelar-gateway/src/event.rs, contracts/axelar-gateway/src/test.rs, contracts/axelar-soroban-interfaces/src/axelar_gateway.rs
[AXE-6062](https://axelarnetwork.atlassian.net/browse/AXE-6062)
[AXE-6062]: https://axelarnetwork.atlassian.net/browse/AXE-6062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(gateway): emit epoch on rotate signers event

contracts/axelar-gateway/src/contract.rs, contracts/axelar-soroban-interfaces/src/axelar_gateway.rs
[AXE-6063](https://axelarnetwork.atlassian.net/browse/AXE-6063)
[AXE-6063]: https://axelarnetwork.atlassian.net/browse/AXE-6063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(gateway): add upgrade and version

contracts/axelar-gateway/src/auth.rs, contracts/axelar-gateway/src/event.rs, contracts/axelar-gateway/src/test.rs, integration-tests/tests/gmp.rs
[AXE-6092](https://axelarnetwork.atlassian.net/browse/AXE-6092)
[AXE-6092]: https://axelarnetwork.atlassian.net/browse/AXE-6092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: update call contract and rotate signers event

contracts/axelar-gateway/src/contract.rs, contracts/axelar-gateway/src/storage_types.rs, contracts/axelar-gateway/src/test.rs, contracts/axelar-gateway/src/testutils.rs, contracts/axelar-soroban-interfaces/src/axelar_executable.rs, contracts/axelar-soroban-interfaces/src/axelar_gateway.rs, contracts/axelar-soroban-interfaces/src/types.rs, integration-tests/tests/gmp.rs
[AXE-6097](https://axelarnetwork.atlassian.net/browse/AXE-6097)
[AXE-6097]: https://axelarnetwork.atlassian.net/browse/AXE-6097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: update message approval args consistent

contracts/axelar-gateway/src/contract.rs, contracts/axelar-gateway/src/event.rs, contracts/axelar-gateway/src/storage_types.rs, contracts/axelar-gateway/src/test_auth.rs, contracts/axelar-gateway/src/test_gateway.rs, contracts/axelar-gateway/src/testutils.rs, contracts/axelar-soroban-interfaces/src/axelar_gateway.rs, integration-tests/tests/gmp.rs
[AXE-6076](https://axelarnetwork.atlassian.net/browse/AXE-6076)
[AXE-6076]: https://axelarnetwork.atlassian.net/browse/AXE-6076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(gateway): add ownership for upgrade

contracts/axelar-gas-service/src/event.rs, contracts/axelar-gas-service/src/test.rs, contracts/axelar-gateway/src/contract.rs, contracts/axelar-gateway/src/event.rs, contracts/axelar-gateway/src/test_gateway.rs, contracts/axelar-gateway/src/testutils.rs, contracts/axelar-operators/src/event.rs, contracts/axelar-operators/src/test.rs, integration-tests/tests/gmp.rs
[AXE-6138]
[AXE-6138]: https://axelarnetwork.atlassian.net/browse/AXE-6138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(axelar-gateway)!: use more readable event symbols

README.md, optimize.sh
[AXE-6471](https://axelarnetwork.atlassian.net/browse/AXE-6471)
[AXE-6471]: https://axelarnetwork.atlassian.net/browse/AXE-6471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: update soroban cli cmd to stellar

contracts/interchain-token/Cargo.toml
[AXE-6533](https://axelarnetwork.atlassian.net/browse/AXE-6533)
[AXE-6533]: https://axelarnetwork.atlassian.net/browse/AXE-6533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: rename dev_dependencies to dev-dependencies in interchain token

Cargo.lock, Cargo.toml, contracts/axelar-gas-service/src/contract.rs, contracts/axelar-gas-service/tests/test.rs, contracts/gmp-example/Cargo.toml, contracts/gmp-example/src/contract.rs, contracts/gmp-example/src/error.rs, contracts/gmp-example/src/event.rs, contracts/gmp-example/src/lib.rs, contracts/gmp-example/src/storage_types.rs, contracts/gmp-example/tests/test.rs
[AXE-6086](https://axelarnetwork.atlassian.net/browse/AXE-6086)
[AXE-6086]: https://axelarnetwork.atlassian.net/browse/AXE-6086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: gmp example contract

contracts/example/src/contract.rs, contracts/example/src/error.rs, contracts/example/src/lib.rs, contracts/example/src/storage_types.rs, contracts/example/tests/test.rs
[AXE-6584](https://axelarnetwork.atlassian.net/browse/AXE-6584)
[AXE-6584]: https://axelarnetwork.atlassian.net/browse/AXE-6584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(example): add contract constructor

contracts/interchain-token-service/src/lib.rs, contracts/interchain-token-service/src/tests/test.rs
[AXE-6575](https://axelarnetwork.atlassian.net/browse/AXE-6575)
[AXE-6575]: https://axelarnetwork.atlassian.net/browse/AXE-6575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(its): move test.rs to tests folder

contracts/axelar-gas-service/src/contract.rs, contracts/axelar-gas-service/src/event.rs, contracts/axelar-gas-service/src/interface.rs, contracts/axelar-gas-service/tests/test.rs
- Add `spender` in add_gas
- Use `transfer` instead of `transfer_from`
=> fix(axelar-gas-service)!: fix axlear gas service add_gas

.github/workflows/codecov.yaml, .github/workflows/compile.yaml, .github/workflows/lint.yaml, .github/workflows/test.yaml, contracts/interchain-token-service/tests/interchain_transfer.rs, contracts/interchain-token-service/tests/utils/mod.rs
[AXE-6855]
[AXE-6855]: https://axelarnetwork.atlassian.net/browse/AXE-6855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ci: switch rust actions in workflows

contracts/axelar-gateway/src/auth.rs, contracts/axelar-gateway/src/error.rs
[AXE-6868](https://axelarnetwork.atlassian.net/browse/AXE-6868)
[AXE-6868]: https://axelarnetwork.atlassian.net/browse/AXE-6868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(gateway): differentiate gateway errors

contracts/axelar-gateway/tests/gateway.rs, contracts/axelar-operators/tests/test.rs, packages/axelar-std/src/error.rs, packages/axelar-std/src/testutils.rs
[AXE-7174]
[AXE-7174]: https://axelarnetwork.atlassian.net/browse/AXE-7174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: check auth is used in assert_auth

contracts/axelar-gas-service/CHANGELOG.md, contracts/axelar-gateway/CHANGELOG.md, contracts/axelar-operators/CHANGELOG.md, contracts/interchain-token-service/CHANGELOG.md, contracts/interchain-token/CHANGELOG.md, contracts/upgrader/CHANGELOG.md, packages/axelar-std-derive/CHANGELOG.md, packages/axelar-std/CHANGELOG.md
Package: stellar-axelar-gas-service 0.1.0 -> 0.1.0
Changes:
- *(axelar-gateway)* Increase gateway coverage and add coverage report ([#25](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/25)) - ([2c6f9f9](https://github.com/axelarnetwork/axelar-cgp-stellar/commit/2c6f9f96f59b74d521aec090d9e31908ab307134))
- *(gas-service)* Add contract constructor ([#72](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/72)) - ([2d5e74c](https://github.com/axelarnetwork/axelar-cgp-stellar/commit/2d5e74c5eaa07eb4ede4a287d13d6be25c5212b7))
- *(gas-service)* Add gas function in gas service ([#59](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/59)) - ([270bd85](https://github.com/axelarnetwork/axelar-cgp-stellar/commit/270bd85c32f9cd90285134be1b4a9fd2878402ff))
- *(gas-service)* …
=> chore: release v0.1.0

Cargo.toml, LICENSE-APACHE, LICENSE-MIT
[AXE-7188](https://axelarnetwork.atlassian.net/browse/AXE-7188)
[AXE-7188]: https://axelarnetwork.atlassian.net/browse/AXE-7188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add license

contracts/interchain-token-service/src/contract.rs, contracts/interchain-token-service/src/error.rs, contracts/interchain-token-service/tests/executable.rs, contracts/interchain-token-service/tests/execute.rs, contracts/interchain-token-service/tests/flow_limit.rs, contracts/interchain-token-service/tests/testdata/interchain_transfer_execute_succeeds.golden, contracts/interchain-token-service/tests/testdata/interchain_transfer_message_execute_succeeds.golden, contracts/interchain-token-service/tests/utils/mod.rs
[AXE-7190]
[AXE-7190]: https://axelarnetwork.atlassian.net/browse/AXE-7190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(interchain-token-service): validate its hub source address

Cargo.lock, Cargo.toml, contracts/axelar-gas-service/tests/test.rs, contracts/axelar-gateway/Cargo.toml, contracts/axelar-gateway/src/testutils.rs, contracts/axelar-gateway/tests/gateway.rs, contracts/interchain-token-service/tests/executable.rs, contracts/interchain-token-service/tests/flow_limit.rs, contracts/interchain-token-service/tests/register_canonical_token.rs, packages/axelar-std/src/error.rs, packages/axelar-std/src/interfaces/upgradable.rs
[AXE-7196]
[AXE-7196]: https://axelarnetwork.atlassian.net/browse/AXE-7196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update workspace dependencies

Cargo.lock, Cargo.toml, contracts/axelar-gas-service/CHANGELOG.md, contracts/axelar-gas-service/Cargo.toml, contracts/axelar-gateway/CHANGELOG.md, contracts/axelar-gateway/Cargo.toml, contracts/axelar-operators/CHANGELOG.md, contracts/axelar-operators/Cargo.toml, contracts/interchain-token-service/CHANGELOG.md, contracts/interchain-token-service/Cargo.toml, contracts/interchain-token/CHANGELOG.md, contracts/interchain-token/Cargo.toml, contracts/upgrader/CHANGELOG.md, contracts/upgrader/Cargo.toml, packages/axelar-std-derive/CHANGELOG.md, packages/axelar-std-derive/Cargo.toml, packages/axelar-std/CHANGELOG.md, packages/axelar-std/Cargo.toml
Package: stellar-axelar-std 0.1.0 -> 0.1.1
Changes:
- *(axelar-std)* Add derive macro unit tests ([#170](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/170)) - ([f52dded](https://github.com/axelarnetwork/axelar-cgp-stellar/commit/f52ddede4fef910361a306d47b2f248cd3897923))
* @nbayindirli
Package: stellar-axelar-std-derive 0.1.0 -> 0.1.1
Changes:
- *(axelar-std)* Add derive macro unit tests ([#170](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/170)) - ([f52dded](https://github.com/axelarnetwork/axelar-cgp-stellar/commit/f52ddede4fef910361a306d47b2f248cd3897923))
* @nbayindirli
Package: stellar-axelar-gas-service 0.1.0 -> 0.1.1
Changes:
- Updated the following local packages: stellar-axelar-std, stellar-axelar-std - …
=> chore: release v0.1.1

Cargo.lock, Cargo.toml, contracts/stellar-axelar-gas-service/CHANGELOG.md, contracts/stellar-axelar-gas-service/Cargo.toml, contracts/stellar-axelar-gateway/CHANGELOG.md, contracts/stellar-axelar-gateway/Cargo.toml, contracts/stellar-axelar-operators/CHANGELOG.md, contracts/stellar-axelar-operators/Cargo.toml, contracts/stellar-interchain-token-service/CHANGELOG.md, contracts/stellar-interchain-token-service/Cargo.toml, contracts/stellar-interchain-token/CHANGELOG.md, contracts/stellar-interchain-token/Cargo.toml, contracts/stellar-upgrader/CHANGELOG.md, contracts/stellar-upgrader/Cargo.toml, packages/stellar-axelar-std-derive/CHANGELOG.md, packages/stellar-axelar-std-derive/Cargo.toml, packages/stellar-axelar-std/CHANGELOG.md, packages/stellar-axelar-std/Cargo.toml
Package: stellar-axelar-gas-service 0.1.0 -> 0.2.0
Changes:
- [**breaking**] Rename packages and move tests under src ([#185](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/185)) - ([804c962](https://github.com/axelarnetwork/axelar-cgp-stellar/commit/804c962a667a7889c447decf8155c4f56c7b1bdb))
* @ahramy
Package: stellar-axelar-std 0.1.0 -> 0.2.0
Changes:
- [**breaking**] Rename packages and move tests under src ([#185](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/185)) - ([804c962](https://github.com/axelarnetwork/axelar-cgp-stellar/commit/804c962a667a7889c447decf8155c4f56c7b1bdb))
* @ahramy
Package: stellar-axelar-std-derive 0.1.1 -> 0.2.0
Changes:
- [**breaking**] Rename packages and move tests under src ([#185](https://github.com/axelarnetwork/axelar-cgp-stellar/pul …
=> chore: release v0.2.0

Cargo.lock, Cargo.toml, contracts/stellar-axelar-gas-service/CHANGELOG.md, contracts/stellar-axelar-gas-service/Cargo.toml, contracts/stellar-axelar-gateway/CHANGELOG.md, contracts/stellar-axelar-gateway/Cargo.toml, contracts/stellar-axelar-operators/CHANGELOG.md, contracts/stellar-axelar-operators/Cargo.toml, contracts/stellar-interchain-token-service/CHANGELOG.md, contracts/stellar-interchain-token-service/Cargo.toml, contracts/stellar-interchain-token/CHANGELOG.md, contracts/stellar-interchain-token/Cargo.toml, contracts/stellar-upgrader/CHANGELOG.md, contracts/stellar-upgrader/Cargo.toml, packages/stellar-axelar-std-derive/CHANGELOG.md, packages/stellar-axelar-std-derive/Cargo.toml, packages/stellar-axelar-std/CHANGELOG.md, packages/stellar-axelar-std/Cargo.toml
Package: stellar-axelar-gas-service 0.2.0 -> 0.2.1
Changes:
- Update description for packages ([#196](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/196)) - ([a20b6ab](https://github.com/axelarnetwork/axelar-cgp-stellar/commit/a20b6ab2633b3ca407c440b9ce35ff0071384638))
* @ahramy
Package: stellar-axelar-std 0.2.0 -> 0.2.1
Changes:
- Update description for packages ([#196](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/196)) - ([a20b6ab](https://github.com/axelarnetwork/axelar-cgp-stellar/commit/a20b6ab2633b3ca407c440b9ce35ff0071384638))
* @ahramy
Package: stellar-axelar-std-derive 0.2.0 -> 0.2.1
Changes:
- *(axelar-std)* Feature gate exported interfaces ([#192](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/192)) - …
=> chore: release v0.2.1

.github/workflows/test.yaml, contracts/stellar-interchain-token-service/src/tests/executable.rs
=> ci: fail on warnings

contracts/stellar-example/src/tests/test.rs, contracts/stellar-example/src/tests/testdata/its_example.golden
=> test(example): use gateway, ITS, and gas service testutils

codecov.yml
[AXE-7253](https://axelarnetwork.atlassian.net/browse/AXE-7253)
[AXE-7253]: https://axelarnetwork.atlassian.net/browse/AXE-7253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add codecov configuration

Cargo.lock, Cargo.toml, contracts/stellar-interchain-token-service/CHANGELOG.md, contracts/stellar-interchain-token-service/Cargo.toml, contracts/stellar-interchain-token/CHANGELOG.md, contracts/stellar-interchain-token/Cargo.toml, contracts/stellar-upgrader/CHANGELOG.md, contracts/stellar-upgrader/Cargo.toml
Package: stellar-interchain-token-service 0.3.0 -> 0.3.1
Changes:
- *(interchain-token)* Unimplemented notice for SAC methods ([#225](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/225)) - ([8c31f8e](https://github.com/axelarnetwork/axelar-cgp-stellar/commit/8c31f8e6f56ebed5909c0e448e2758ce988aadbe))
- *(example)* Increase ITS coverage ([#221](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/221)) - ([996f2bc](https://github.com/axelarnetwork/axelar-cgp-stellar/commit/996f2bc8524d4c25005f5bd2b5b026b0dfaef2da))
* @nbayindirli
* @milapsheth
Package: stellar-interchain-token 0.2.3 -> 0.2.4
Changes:
- *(interchain-token)* Unimplemented notice for SAC methods ([#225](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/225)) - …
=> chore: release

.cargo/config.toml, .github/workflows/upload-docs.yaml, contracts/stellar-axelar-gas-service/src/interface.rs, contracts/stellar-axelar-operators/src/interface.rs, contracts/stellar-interchain-token-service/src/executable.rs, contracts/stellar-interchain-token-service/src/interface.rs, contracts/stellar-interchain-token/src/interface.rs, contracts/stellar-token-manager/src/interface.rs, packages/stellar-axelar-std-derive/src/lib.rs
[AXE-7339]
[AXE-7339]: https://axelarnetwork.atlassian.net/browse/AXE-7339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: fix docs publish action

contracts/stellar-axelar-operators/src/contract.rs, contracts/stellar-axelar-operators/src/lib.rs, contracts/stellar-axelar-operators/src/storage.rs, contracts/stellar-axelar-operators/src/storage_types.rs, contracts/stellar-axelar-operators/src/testdata/ensure_data_key_storage_schema_is_unchanged.golden
=> refactor(axelar-operators): use contractstorage

contracts/stellar-axelar-operators/src/contract.rs, contracts/stellar-axelar-operators/src/storage.rs, contracts/stellar-axelar-operators/src/testdata/ensure_data_key_storage_schema_is_unchanged.golden
=> refactor(axelar-operators)!: rename Operators status to Operator

contracts/stellar-axelar-gateway/src/contract.rs, contracts/stellar-axelar-operators/src/contract.rs, contracts/stellar-interchain-token-service/src/contract.rs, contracts/stellar-interchain-token/src/contract.rs
=> fix: remove redundant ttl extensions

packages/stellar-axelar-std/src/ttl.rs
[AXE-7366](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/21?selectedIssue=AXE-7366)
[AXE-7366]: https://axelarnetwork.atlassian.net/browse/AXE-7366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: increase threshold for extending storage rent

.github/workflows/reusable-build.yaml
[AXE-7976](https://axelarnetwork.atlassian.net/browse/AXE-7976)
- failed gh action: https://github.com/axelarnetwork/axelar-cgp-stellar/actions/runs/13713965818/job/38355464356
[AXE-7976]: https://axelarnetwork.atlassian.net/browse/AXE-7976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: stellar cli failure on the reusable build

contracts/stellar-interchain-token-service/src/contract.rs, packages/stellar-axelar-std-derive/src/lib.rs
[AXE-8258](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/21?selectedIssue=AXE-8258)
[AXE-8258]: https://axelarnetwork.atlassian.net/browse/AXE-8258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(interchain-token-service): remove redundant token_id_config_with_extended_ttl function

contracts/stellar-interchain-token-service/src/token_metadata.rs
[AXE-8255](https://axelarnetwork.atlassian.net/browse/AXE-8255)
[AXE-8255]: https://axelarnetwork.atlassian.net/browse/AXE-8255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: optimize token metadata to skip external calls for native token

contracts/stellar-interchain-token-service/src/contract.rs, contracts/stellar-interchain-token-service/src/tests/trusted_chain.rs
[AXE-8298](https://axelarnetwork.atlassian.net/browse/AXE-8298)
[AXE-8298]: https://axelarnetwork.atlassian.net/browse/AXE-8298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(interchain-token-service): allow operator to manage trusted chains

.release-plz.toml
toml config example: https://release-plz.dev/docs/config
=> chore: remove dummy contract from release

.github/workflows/release-dry-run.yaml, .github/workflows/release-manual.yaml, .github/workflows/release-upload-to-r2.yaml, .github/workflows/release.yaml
[AXE-8492](https://axelarnetwork.atlassian.net/browse/AXE-8492)
- Dry Run Test: https://github.com/axelarnetwork/axelar-cgp-soroban-testing/actions/runs/14319039058
- Upload to R2 Test: https://github.com/axelarnetwork/axelar-cgp-soroban-testing/actions/runs/14319837771
- Release Test: https://github.com/axelarnetwork/axelar-cgp-soroban-testing/actions/runs/14319180125
[AXE-8492]: https://axelarnetwork.atlassian.net/browse/AXE-8492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: release github action to have dry run and skip publish release

contracts/stellar-interchain-token-service/src/migrate.rs, packages/stellar-axelar-std/src/error.rs
This is a follow-up PR: https://github.com/axelarnetwork/axelar-amplifier-stellar/pull/334
=> fix(interchain-token-service): optimize code for creating upgrade auth entires

contracts/stellar-interchain-token-service/src/contract.rs, contracts/stellar-interchain-token-service/src/event.rs, contracts/stellar-interchain-token-service/src/tests/testdata/interchain_transfer_canonical_token_send_succeeds.golden, contracts/stellar-interchain-token-service/src/tests/testdata/interchain_transfer_send_succeeds.golden, contracts/stellar-interchain-token-service/src/tests/testdata/interchain_transfer_send_succeeds_without_gas_token.golden, packages/stellar-axelar-std-derive/src/contractimpl.rs
[AXE-9346](https://axelarnetwork.atlassian.net/browse/AXE-9346)
[AXE-9346]: https://axelarnetwork.atlassian.net/browse/AXE-9346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(interchain-token-service): emit data_hash instead of data in InterchainTransferSentEvent

.github/workflows/stellar-expert-release.yml
[AXE-9708](https://axelarnetwork.atlassian.net/browse/AXE-9708)
[AXE-9708]: https://axelarnetwork.atlassian.net/browse/AXE-9708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add stellar expert release

contracts/stellar-interchain-token-service/src/contract.rs, contracts/stellar-interchain-token-service/src/event.rs, contracts/stellar-interchain-token-service/src/interface.rs, contracts/stellar-interchain-token-service/src/tests/mod.rs, contracts/stellar-interchain-token-service/src/tests/register_token_metadata.rs, contracts/stellar-interchain-token-service/src/tests/testdata/register_token_metadata_succeeds.golden
[AXE-9730](https://axelarnetwork.atlassian.net/browse/AXE-9730)
[AXE-9730]: https://axelarnetwork.atlassian.net/browse/AXE-9730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(interchain-token-service): add register_token_metadata hub message type

contracts/stellar-interchain-token-service/src/tests/execute.rs, contracts/stellar-interchain-token-service/src/token_handler.rs, contracts/stellar-interchain-token-service/src/token_manager.rs
[AXE-9815](https://axelarnetwork.atlassian.net/browse/AXE-9815)
[AXE-9815]: https://axelarnetwork.atlassian.net/browse/AXE-9815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(interchain-token-service): use mint for mint burn token manager type

contracts/stellar-interchain-token-service/src/contract.rs, contracts/stellar-interchain-token-service/src/interface.rs, contracts/stellar-interchain-token-service/src/tests/mod.rs, contracts/stellar-interchain-token-service/src/tests/transfer_token_admin.rs, contracts/stellar-interchain-token-service/src/token_manager.rs
[AXE-9870](https://axelarnetwork.atlassian.net/browse/AXE-9870)
[AXE-9870]: https://axelarnetwork.atlassian.net/browse/AXE-9870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(interchain-token-service): add transfer token admin function
