axelarnetwork/axelar-amplifier-stellar

contracts/axelar-auth-verifier/src/contract.rs, contracts/axelar-auth-verifier/src/test.rs, contracts/axelar-auth-verifier/src/testutils.rs, contracts/axelar-soroban-interfaces/src/types.rs
[AXE-4337]
[AXE-4337]: https://axelarnetwork.atlassian.net/browse/AXE-4337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(AxelarAuthVerifier): use u128 for weights and threshold

Cargo.lock, Cargo.toml, contracts/axelar-gas-service/src/test.rs
closes [AXE-6310](https://axelarnetwork.atlassian.net/browse/AXE-6310)
We are currently on `soroban-sdk = { version = "21.0.1-preview.3" }`, which is outdated and has some issues with future rust versions (tests would always abort, fixed by https://github.com/stellar/rs-soroban-sdk/pull/1333). Was told that sdk versions under the same major version guarantee no breaking changes and that the [software-versions page](https://developers.stellar.org/docs/networks/software-versions#protocol-21-mainnet-june-18-2024) is incorrectly claiming that mainnet is running the preview version.
We don't need to always be on the latest version, but staying on a preview version doesn't seem ideal.
- upgraded `soroban_sdk` version to `21.7.6`, the latest one at the time of writing
- replace uses of …
=> feat: upgrade `soroban-sdk` version to `v21.7.6`

contracts/axelar-gateway/src/auth.rs, contracts/axelar-gateway/src/contract.rs
[AXE-6098](https://axelarnetwork.atlassian.net/browse/AXE-6098)
- add ttl extension for instance storage when validate_proof is called
[AXE-6098]: https://axelarnetwork.atlassian.net/browse/AXE-6098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(gateway): add instance ttl extension

contracts/interchain-token-service/src/lib.rs, contracts/interchain-token-service/src/types.rs
[AXE-6064](https://axelarnetwork.atlassian.net/browse/AXE-6064)
- add ITS message types
- add token manageger types
- define ITS messages with Soroban types
[AXE-6064]: https://axelarnetwork.atlassian.net/browse/AXE-6064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(its): add ITS message types

.github/workflows/codecov.yaml, .github/workflows/compile.yaml, .github/workflows/lint.yaml, .github/workflows/test.yaml, Cargo.lock, Cargo.toml
closes https://axelarnetwork.atlassian.net/browse/AXE-6571
Testnet upgraded to v22 today, we need to keep the version compatible with the network so that contracts can execute
from [the upgrade guide](https://stellar.org/blog/developers/protocol-22-upgrade-guide), stable builds of the software will be available on November 19, so we'll shift off the "rc" version then
=> feat: upgrade soroban-sdk version to v22.0.0-rc.3

.github/actions/compile-stellar/action.yaml
* use `--features opt` flag when installing, which is required when optimizing contracts
* set `-x` permission before caching
* indicate missing `shell` field in one of the steps
=> ci: install stellar CLI with opt flag

contracts/axelar-gas-service/src/contract.rs, contracts/axelar-gas-service/src/error.rs, contracts/axelar-gas-service/src/storage_types.rs, contracts/axelar-gas-service/tests/test.rs, contracts/example/tests/test.rs
closes https://axelarnetwork.atlassian.net/browse/AXE-6580
similar to #69 
added a getter for gas_collector to reduce some code duplication & to move the unit test which was querying the contract env directly to an integration test which calls this new method instead.
=> feat(gas-service): add contract constructor

contracts/axelar-gateway/src/auth.rs, contracts/axelar-gateway/src/contract.rs, contracts/axelar-gateway/src/error.rs, contracts/axelar-gateway/src/storage_types.rs, contracts/axelar-gateway/src/testutils.rs, contracts/axelar-gateway/tests/test.rs, contracts/example/tests/test.rs, integration-tests/tests/gmp.rs, integration-tests/tests/upgrade.rs
closes https://axelarnetwork.atlassian.net/browse/AXE-6581
similar to #69
most of the changes are to the tests
- `testutils::initialize` now returns the `contract_id` it generated since it doesn't depend on a `client` anymore (`contract_id` is needed  to make a `client`) 
- remove instances of initializing after setup_env (they are handled in `setup_env` now)
- setup_env now requires passing in values for `num_signers` and `minimum_rotation_delay`. Where there was not already a value defined (i.e. tests that did not require initializing), defaulted to `setup_env(1, 5)`
- setup_env in `auth.rs` and `tests/test.rs` doesn't return `contract_id`, instead prefer using `client.address` where possible
- update `validate_message` to expect 1 event because of the event emitted while initializing
=> feat(gateway): add contract constructor

Cargo.lock, Cargo.toml, contracts/axelar-gas-service/Cargo.toml, contracts/axelar-gas-service/src/contract.rs, contracts/axelar-gas-service/src/interface.rs, contracts/axelar-gas-service/src/lib.rs, contracts/axelar-gateway/Cargo.toml, contracts/axelar-gateway/src/contract.rs, contracts/axelar-gateway/src/interface.rs, contracts/axelar-gateway/src/lib.rs, contracts/axelar-gateway/src/testutils.rs, contracts/axelar-gateway/tests/test.rs, contracts/example/Cargo.toml
[AXE-6666]
This PR adds support for a `library` feature that allows soroban contracts to be exported as libraries, i.e without entrypoints to prevent issues with entrypoint name collisions.
`soroban contract build` now works without name collision issues.
- A `testutils` feature is now also required, since Rust doesn't seem to allow declaring a dependency with `features = ["library"]` but a dev dependency with `features = []`, which I believe is because cargo features need to be additive (although need to dive more into). And the actual contract needs to be available in tests.
- Another consequence of this is that it enforces that private methods don't get included as contract entrypoints, since the trait implementation won't allow it
- The Interface trait can also extend other Interfaces …
=> feat: allow exporting soroban contract crates are libraries

contracts/interchain-token-service/src/contract.rs, contracts/interchain-token-service/src/error.rs, contracts/interchain-token-service/src/storage_types.rs, contracts/interchain-token-service/src/test.rs, contracts/interchain-token/src/contract.rs, contracts/interchain-token/src/error.rs, contracts/interchain-token/src/lib.rs, contracts/interchain-token/src/storage_types.rs, contracts/interchain-token/tests/test.rs
closes https://axelarnetwork.atlassian.net/browse/AXE-6583
similar to #69 
only thing of note was that the `interchain-token` `ContractError` type only had two variants, both of which were removed. So I just commented it out (could just be deleted instead?)
=> feat(interchain-token-service,interchain-token): add contract constructor

contracts/interchain-token-service/src/contract.rs, contracts/interchain-token-service/tests/test.rs
`tests/` directory for ITS was at the wrong level of the file tree
=> fix(its): move ITS test directory to the correct level

Cargo.lock, Cargo.toml, contracts/axelar-gas-service/src/contract.rs, contracts/axelar-gas-service/src/event.rs, contracts/axelar-gas-service/src/interface.rs, contracts/interchain-token-service/Cargo.toml, contracts/interchain-token-service/src/contract.rs, contracts/interchain-token-service/src/error.rs, contracts/interchain-token-service/src/event.rs, contracts/interchain-token-service/src/interface.rs, contracts/interchain-token-service/src/lib.rs, contracts/interchain-token-service/src/storage_types.rs, contracts/interchain-token-service/tests/test.rs
[AXE-6709](https://axelarnetwork.atlassian.net/browse/AXE-6709)
[AXE-6709]: https://axelarnetwork.atlassian.net/browse/AXE-6709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(its): add skeleton code for its token deployment

contracts/axelar-gas-service/src/contract.rs
=> refactor(axelar-gas-service): move run_migration into separate impl block

.github/workflows/upload-docs.yaml, README.md, packages/axelar-soroban-std/src/error.rs
[AXE-6854]
This PR adds a workflow to start deploying rust docs to github pages for this repo
https://axelarnetwork.github.io/axelar-cgp-soroban/
[AXE-6854]: https://axelarnetwork.atlassian.net/browse/AXE-6854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: upload soroban docs to gh pages

Cargo.lock, Cargo.toml, contracts/interchain-token-service/Cargo.toml, contracts/interchain-token-service/src/abi.rs, contracts/interchain-token-service/tests/interchain_transfer.rs, contracts/interchain-token-service/tests/message_routing.rs, contracts/interchain-token-service/tests/utils/mod.rs, packages/axelar-soroban-std/Cargo.toml, packages/axelar-soroban-std/src/traits.rs
[AXE-6849](https://axelarnetwork.atlassian.net/browse/AXE-6849)
[AXE-6849]: https://axelarnetwork.atlassian.net/browse/AXE-6849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(its): add BytesExt trait

contracts/interchain-token-service/src/contract.rs, contracts/interchain-token-service/src/event.rs, contracts/interchain-token-service/src/executable.rs, contracts/interchain-token-service/src/lib.rs, contracts/interchain-token-service/src/token_handler.rs, contracts/interchain-token-service/tests/executable.rs, contracts/interchain-token-service/tests/interchain_transfer.rs, contracts/interchain-token-service/tests/testdata/interchain_transfer_execute_succeeds.golden, contracts/interchain-token-service/tests/testdata/interchain_transfer_receive_succeeds.golden
[AXE-6871]
[AXE-6871]: https://axelarnetwork.atlassian.net/browse/AXE-6871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(interchain-token-service): add interchain token executable

contracts/interchain-token-service/src/contract.rs, contracts/interchain-token-service/src/interface.rs, contracts/interchain-token-service/tests/deploy_remote_interchain_token.rs
[AXE-6985](https://axelarnetwork.atlassian.net/browse/AXE-6985)
[AXE-6985]: https://axelarnetwork.atlassian.net/browse/AXE-6985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(interchain-token-service): update error handling for token id config

contracts/example/tests/test.rs, contracts/interchain-token-service/tests/deploy_remote_canonical_token.rs, contracts/interchain-token-service/tests/deploy_remote_interchain_token.rs, packages/axelar-soroban-std/src/testutils.rs
(AXE-6986)[https://axelarnetwork.atlassian.net/browse/AXE-6986]
=> chore: simplify auth test utils

Cargo.lock, contracts/interchain-token-service/Cargo.toml, contracts/interchain-token-service/src/lib.rs
[AXE-6850](https://axelarnetwork.atlassian.net/browse/AXE-6850)
[AXE-6850]: https://axelarnetwork.atlassian.net/browse/AXE-6850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(interchain-token-service): library export

Cargo.lock, packages/axelar-soroban-std-derive/Cargo.toml
The axelar-soroban-std package imports the soroban-sdk, and also imports the axelar-soroban-std-derive package, which in turn also imported the soroban-sdk. When now the testutils feature was active, the compiler couldn't resolve properly which soroban-sdk/testutils feature should get activated. By removing the soroban-sdk dependency from the derive package the ambiguity could be resolved and single contracts are compilable again without compiling the entire workspace
=> fix: make single contracts compilable again

contracts/interchain-token-service/src/contract.rs, contracts/interchain-token-service/src/error.rs, contracts/interchain-token-service/tests/deploy_remote_interchain_token.rs, contracts/interchain-token-service/tests/interchain_transfer.rs
[AXE-7104](https://axelarnetwork.atlassian.net/browse/AXE-7101)
Replaces work from [#135](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/135) following the update of package names in [#145](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/145/files).
Additionally, comments from [#135](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/135) are resolved in this PR.
Adds two checks recommended by FYEO initial security review (https://gofyeo.slack.com/files/UBB212K7X/F088VV30JDN/axelar_-_security_code_review___axelar_-_soroban_v0.1.pdf)
[AXE-7104]: https://axelarnetwork.atlassian.net/browse/AXE-7104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(interchain-token-service): add destination validation checks

contracts/interchain-token-service/src/contract.rs, contracts/interchain-token-service/src/interface.rs
[AXE-7101](https://axelarnetwork.atlassian.net/browse/AXE-7101)
[AXE-7101]: https://axelarnetwork.atlassian.net/browse/AXE-7101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs(interchain-token-service): move entrypoint docstring to interface

optimize.sh
[AXE-7185](https://axelarnetwork.atlassian.net/browse/AXE-7185)
[AXE-7185]: https://axelarnetwork.atlassian.net/browse/AXE-7185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(script): update optimize script to resolve deployment error

contracts/interchain-token-service/src/contract.rs, contracts/interchain-token-service/src/flow_limit.rs, contracts/interchain-token-service/src/interface.rs, contracts/interchain-token-service/tests/flow_limit.rs
[AXE-7172](https://axelarnetwork.atlassian.net/browse/AXE-7172)
Replaces work from [#144](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/144) following the update of package names in [#145](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/145/files)
[AXE-7172]: https://axelarnetwork.atlassian.net/browse/AXE-7172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(interchain-token-service): fix flow limit storage and testing

contracts/axelar-gas-service/CHANGELOG.md, contracts/axelar-gateway/CHANGELOG.md, contracts/axelar-operators/CHANGELOG.md, contracts/interchain-token-service/CHANGELOG.md, contracts/interchain-token/CHANGELOG.md, contracts/upgrader/CHANGELOG.md, packages/axelar-std-derive/CHANGELOG.md, packages/axelar-std/CHANGELOG.md
Package: stellar-axelar-gas-service 0.1.0 -> 0.1.0
Changes:
- *(axelar-gateway)* Increase gateway coverage and add coverage report ([#25](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/25)) - ([2c6f9f9](https://github.com/axelarnetwork/axelar-cgp-stellar/commit/2c6f9f96f59b74d521aec090d9e31908ab307134))
- *(gas-service)* Add contract constructor ([#72](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/72)) - ([2d5e74c](https://github.com/axelarnetwork/axelar-cgp-stellar/commit/2d5e74c5eaa07eb4ede4a287d13d6be25c5212b7))
- *(gas-service)* Add gas function in gas service ([#59](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/59)) - ([270bd85](https://github.com/axelarnetwork/axelar-cgp-stellar/commit/270bd85c32f9cd90285134be1b4a9fd2878402ff))
- *(gas-service)* …
=> chore: release v0.1.0

packages/axelar-std-derive/src/upgradable.rs
`syn::Type` doesn't implement `Debug`
=> fix: remove debug dependency from upgradable

Cargo.lock, Cargo.toml, contracts/stellar-axelar-gas-service/CHANGELOG.md, contracts/stellar-axelar-gas-service/Cargo.toml, contracts/stellar-axelar-gateway/CHANGELOG.md, contracts/stellar-axelar-gateway/Cargo.toml, contracts/stellar-axelar-operators/CHANGELOG.md, contracts/stellar-axelar-operators/Cargo.toml, contracts/stellar-interchain-token-service/CHANGELOG.md, contracts/stellar-interchain-token-service/Cargo.toml, contracts/stellar-interchain-token/CHANGELOG.md, contracts/stellar-interchain-token/Cargo.toml, contracts/stellar-upgrader/CHANGELOG.md, contracts/stellar-upgrader/Cargo.toml, packages/stellar-axelar-std/CHANGELOG.md, packages/stellar-axelar-std/Cargo.toml
Package: stellar-axelar-gas-service 0.2.1 -> 0.2.2
Changes:
- Move test modules into lib.rs ([#199](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/199)) - ([51a638a](https://github.com/axelarnetwork/axelar-cgp-stellar/commit/51a638a52bdaebc4928aab9e191b28a90e73f338))
* @AttissNgo
Package: stellar-axelar-std 0.2.1 -> 0.2.2
Changes:
- Move test modules into lib.rs ([#199](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/199)) - ([51a638a](https://github.com/axelarnetwork/axelar-cgp-stellar/commit/51a638a52bdaebc4928aab9e191b28a90e73f338))
* @AttissNgo
Package: stellar-axelar-gateway 0.2.1 -> 0.2.2
Changes:
- Move test modules into lib.rs ([#199](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/199)) - ([51a638a](https://github.com/axelarnetwork/axelar-cgp-stellar/co …
=> chore: release v0.2.2

contracts/stellar-axelar-gateway/src/auth.rs, contracts/stellar-axelar-gateway/src/contract.rs, contracts/stellar-axelar-gateway/src/interface.rs, contracts/stellar-axelar-gateway/src/tests/auth.rs, contracts/stellar-axelar-gateway/src/tests/utils/mod.rs, contracts/stellar-axelar-gateway/src/testutils.rs, packages/stellar-axelar-std/src/types.rs
[AXE-7251]
[AXE-7251]: https://axelarnetwork.atlassian.net/browse/AXE-7251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(axelar-gateway): add more queries

Cargo.lock, contracts/stellar-axelar-gateway/Cargo.toml, packages/stellar-axelar-std-derive/Cargo.toml, packages/stellar-axelar-std-derive/src/lib.rs, packages/stellar-axelar-std/Cargo.toml
[AXE-7254]
[AXE-7254]: https://axelarnetwork.atlassian.net/browse/AXE-7254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(axelar-std-derive): cleanup dependencies

Cargo.lock, Cargo.toml, contracts/stellar-axelar-gateway/src/contract.rs, contracts/stellar-interchain-token-service/src/contract.rs, packages/stellar-axelar-std-derive/src/lib.rs, packages/stellar-axelar-std-derive/src/pausable.rs, packages/stellar-axelar-std/src/interfaces/pausable.rs
[AXE-7255]
stellar/rs-soroban-sdk#1426 allows function attributes to be used to check for pause status
[AXE-7255]: https://axelarnetwork.atlassian.net/browse/AXE-7255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(axelar-std-derive): add macro to execute when contract is not paused

Cargo.lock, Cargo.toml, contracts/stellar-axelar-gas-service/CHANGELOG.md, contracts/stellar-axelar-gas-service/Cargo.toml, contracts/stellar-axelar-gateway/CHANGELOG.md, contracts/stellar-axelar-gateway/Cargo.toml, contracts/stellar-axelar-operators/CHANGELOG.md, contracts/stellar-axelar-operators/Cargo.toml, contracts/stellar-interchain-token-service/CHANGELOG.md, contracts/stellar-interchain-token-service/Cargo.toml, contracts/stellar-interchain-token/CHANGELOG.md, contracts/stellar-interchain-token/Cargo.toml, contracts/stellar-token-manager/CHANGELOG.md, contracts/stellar-upgrader/CHANGELOG.md, contracts/stellar-upgrader/Cargo.toml, packages/stellar-axelar-std-derive/CHANGELOG.md, packages/stellar-axelar-std-derive/Cargo.toml, packages/stellar-axelar-std/CHANGELOG.md, packages/stellar-axelar-std/Cargo.toml
Package: stellar-axelar-gas-service 0.2.2 -> 0.3.0
Changes:
- *(axelar-gas-service)* [**breaking**] Switch gas_collector to operator ([#209](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/209)) - ([2553182](https://github.com/axelarnetwork/axelar-cgp-stellar/commit/2553182ca510e4092b2b841e11fc4fcf66be3f75))
- Add docs to contract interfaces ([#175](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/175)) - ([2f17e32](https://github.com/axelarnetwork/axelar-cgp-stellar/commit/2f17e32b33e6d04609c3014e161ce07f9dbbef63))
* @TanvirDeol
* @milapsheth
Package: stellar-axelar-std 0.2.2 -> 0.3.0
Changes:
- *(axelar-gateway)* Add more queries ([#207](https://github.com/axelarnetwork/axelar-cgp-stellar/pull/207)) - ([ca3b486](https://github.com/axelarnetwork/axelar-cgp-stellar/commit/ …
=> chore: release

contracts/stellar-axelar-gas-service/Cargo.toml, contracts/stellar-axelar-gateway/Cargo.toml, contracts/stellar-axelar-operators/Cargo.toml, contracts/stellar-example/Cargo.toml, contracts/stellar-interchain-token-service/Cargo.toml, contracts/stellar-interchain-token/Cargo.toml, contracts/stellar-token-manager/Cargo.toml, contracts/stellar-upgrader/Cargo.toml, packages/stellar-axelar-std-derive/Cargo.toml, packages/stellar-axelar-std/Cargo.toml
[AXE-7232](https://axelarnetwork.atlassian.net/browse/AXE-7232)
[AXE-7232]: https://axelarnetwork.atlassian.net/browse/AXE-7232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update package descriptions

contracts/stellar-example/src/storage.rs, contracts/stellar-example/src/testdata/ensure_data_key_storage_schema_is_unchanged.golden, packages/stellar-axelar-std-derive/Cargo.toml, packages/stellar-axelar-std-derive/src/lib.rs, packages/stellar-axelar-std-derive/src/storage.rs, packages/stellar-axelar-std-derive/src/testdata/storage_schema_generation_succeeds.golden, packages/stellar-axelar-std/src/tests/testdata/ensure_data_key_storage_schema_is_unchanged.golden
=> feat(axelar-std-derive): add status support to contractstorage macro

Cargo.lock, contracts/stellar-upgrader/Cargo.toml, contracts/stellar-upgrader/src/lib.rs, contracts/stellar-upgrader/src/tests/atomic_upgrades.rs, contracts/stellar-upgrader/src/tests/utils/dummy_contract.rs, contracts/stellar-upgrader/src/tests/utils/dummy_contract_after_upgrade.rs, contracts/stellar-upgrader/src/tests/utils/testdata/ensure_data_key_storage_schema_is_unchanged.golden
=> refactor(upgrader): use contractstorage

.github/workflows/codecov.yaml, .github/workflows/contract-storage-diff.yaml
removes unnecessary `continue-on-error`
=> chore: rm continue-on-error

.github/workflows/release-dry-run.yaml, .github/workflows/release.yaml
A fix for the release error: https://github.com/axelarnetwork/axelar-amplifier-stellar/actions/runs/14321545102/job/40139292869
```
error: failed to verify package tarball
Caused by:
rustc 1.80.0 is not supported by the following packages:
alloy-primitives@0.8.25 requires rustc 1.81
alloy-sol-macro@0.8.25 requires rustc 1.81
alloy-sol-macro-expander@0.8.25 requires rustc 1.81
alloy-sol-macro-input@0.8.25 requires rustc 1.81
alloy-sol-types@0.8.25 requires rustc 1.81
syn-solidity@0.8.25 requires rustc 1.81
Error: Process completed with exit code 1.
```
=> fix(release): add rust tool chain
